spring:
  sql:
    init:
      mode: always

  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: myuser
    password: secret

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true
    generate-ddl: true

jwt:
  secret-key: aG90ZWxraW5naGVsbG8K
  access-life-time-sec: 86400      # 1일
  refresh-life-time-sec: 15552000  # 6개월 (86400 * 30 * 6(개월))

springdoc:
  default-produces-media-type: application/json