spring:
  sql:
    init:
      mode: always

  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: myuser
    password: secret

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true
    generate-ddl: true
